-- =============================================================================
-- Agrostand — DDL + Row-Level Security (PostgreSQL)
-- Idempotente: executado a cada boot por `initializeDatabase()` com a conexão
-- ADMIN (dona das tabelas). A API conecta com um role sem BYPASSRLS, portanto
-- todas as policies abaixo valem para ela.
--
-- Contexto lido pelas policies (definido por conexão em src/db/index.js):
--   app.user_id → usuário autenticado ('' = anônimo)
--   app.system  → 'on' em fluxos confiáveis do servidor (login, cadastro,
--                 recuperação de senha, denylist de JWT, purga CRON)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS app;

CREATE OR REPLACE FUNCTION app.current_user_id() RETURNS integer
  LANGUAGE sql STABLE AS
$$ SELECT NULLIF(current_setting('app.user_id', true), '')::integer $$;

CREATE OR REPLACE FUNCTION app.is_system() RETURNS boolean
  LANGUAGE sql STABLE AS
$$ SELECT COALESCE(current_setting('app.system', true), '') = 'on' $$;

-- ─── Tabelas ─────────────────────────────────────────────────────────────────
-- Timestamps em TEXT no formato do legado SQLite (UTC 'YYYY-MM-DD HH:MM:SS').

CREATE TABLE IF NOT EXISTS "Usuario" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  sobrenome text NOT NULL,
  email text NOT NULL CONSTRAINT "Usuario_email_unique" UNIQUE,
  telefone text NOT NULL,
  senha_hash text NOT NULL,
  data_cadastro text NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "Endereco" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id integer NOT NULL REFERENCES "Usuario"(id) ON DELETE CASCADE,
  rua text NOT NULL,
  numero text NOT NULL,
  bairro text NOT NULL,
  cep text,
  cidade text NOT NULL,
  uf text NOT NULL,
  zona text NOT NULL CONSTRAINT chk_endereco_zona CHECK (zona IN ('URBANA', 'RURAL'))
);

CREATE TABLE IF NOT EXISTS "Categoria" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL CONSTRAINT "Categoria_nome_unique" UNIQUE,
  descricao text
);

CREATE TABLE IF NOT EXISTS "Anuncio" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anunciante_id integer NOT NULL REFERENCES "Usuario"(id) ON DELETE CASCADE,
  categoria_id integer NOT NULL REFERENCES "Categoria"(id) ON DELETE RESTRICT,
  endereco_id integer NOT NULL REFERENCES "Endereco"(id) ON DELETE RESTRICT,
  nome text NOT NULL,
  descricao text NOT NULL,
  preco double precision NOT NULL,
  data_publicacao text NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  status text NOT NULL DEFAULT 'ATIVO'
    CONSTRAINT chk_anuncio_status CHECK (status IN ('ATIVO', 'EM_LIXEIRA', 'REMOVIDO')),
  data_remocao text
);

CREATE TABLE IF NOT EXISTS "Imagem" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anuncio_id integer NOT NULL REFERENCES "Anuncio"(id) ON DELETE CASCADE,
  url text NOT NULL,
  tipo text NOT NULL CONSTRAINT chk_imagem_tipo CHECK (tipo IN ('PRINCIPAL', 'SECUNDARIA')),
  ordem integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "RecuperacaoSenha" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL REFERENCES "Usuario"(id) ON DELETE CASCADE,
  codigo text NOT NULL,
  expira_em text NOT NULL,
  usado integer NOT NULL DEFAULT 0
);

-- RN17: um cliente não favorita o mesmo anúncio duas vezes; CASCADEs limpam
-- favoritos ao excluir conta (RN20) ou anúncio purgado
CREATE TABLE IF NOT EXISTS "Favorito" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id integer NOT NULL REFERENCES "Usuario"(id) ON DELETE CASCADE,
  anuncio_id integer NOT NULL REFERENCES "Anuncio"(id) ON DELETE CASCADE,
  data_favorito text NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

-- RN19: falhas consecutivas de login por e-mail (bloqueio temporário)
CREATE TABLE IF NOT EXISTS "TentativaLogin" (
  email text PRIMARY KEY,
  tentativas integer NOT NULL DEFAULT 0,
  bloqueado_ate text,
  atualizado_em text NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

-- UC13: denylist de JWTs revogados no logout (purgada de forma amortizada)
CREATE TABLE IF NOT EXISTS "TokenRevogado" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL CONSTRAINT "TokenRevogado_token_hash_unique" UNIQUE,
  expira_em text NOT NULL,
  revogado_em text NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_usuario_email ON "Usuario"(email);
CREATE INDEX IF NOT EXISTS idx_endereco_cliente ON "Endereco"(cliente_id);
CREATE INDEX IF NOT EXISTS idx_anuncio_anunciante_status ON "Anuncio"(anunciante_id, status);
CREATE INDEX IF NOT EXISTS idx_anuncio_categoria_status ON "Anuncio"(categoria_id, status);
CREATE INDEX IF NOT EXISTS idx_anuncio_endereco ON "Anuncio"(endereco_id);
CREATE INDEX IF NOT EXISTS idx_imagem_anuncio ON "Imagem"(anuncio_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_anuncio_imagem_principal
  ON "Imagem"(anuncio_id) WHERE tipo = 'PRINCIPAL';
CREATE INDEX IF NOT EXISTS idx_recuperacaosenha_usuario ON "RecuperacaoSenha"(usuario_id);
CREATE INDEX IF NOT EXISTS idx_favorito_cliente ON "Favorito"(cliente_id);
CREATE INDEX IF NOT EXISTS idx_favorito_anuncio ON "Favorito"(anuncio_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorito_cliente_anuncio ON "Favorito"(cliente_id, anuncio_id);
CREATE INDEX IF NOT EXISTS idx_tentativalogin_bloqueio ON "TentativaLogin"(bloqueado_ate);
CREATE INDEX IF NOT EXISTS idx_tokenrevogado_hash ON "TokenRevogado"(token_hash);
CREATE INDEX IF NOT EXISTS idx_tokenrevogado_expira ON "TokenRevogado"(expira_em);

-- ─── Row-Level Security ──────────────────────────────────────────────────────

ALTER TABLE "Usuario"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Endereco"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Categoria"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Anuncio"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Imagem"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecuperacaoSenha" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Favorito"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TentativaLogin"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TokenRevogado"    ENABLE ROW LEVEL SECURITY;

-- Recria as policies a cada boot para que alterações neste arquivo se apliquem.
DO $$
DECLARE p record;
BEGIN
  FOR p IN
    SELECT policyname, tablename FROM pg_policies
    WHERE schemaname = 'public' AND policyname LIKE 'rls_%'
  LOOP
    EXECUTE format('DROP POLICY %I ON %I', p.policyname, p.tablename);
  END LOOP;
END $$;

-- Usuario: cada um vê/edita/exclui só a própria linha. Dados de vendedor com
-- anúncio visível ficam legíveis (nome/telefone aparecem no anúncio público).
-- Criação de conta só em contexto de sistema (cadastro / login Google).
CREATE POLICY rls_usuario_select ON "Usuario" FOR SELECT USING (
  id = app.current_user_id() OR app.is_system()
  OR EXISTS (SELECT 1 FROM "Anuncio" a WHERE a.anunciante_id = "Usuario".id)
);
CREATE POLICY rls_usuario_insert ON "Usuario" FOR INSERT WITH CHECK (app.is_system());
CREATE POLICY rls_usuario_update ON "Usuario" FOR UPDATE
  USING (id = app.current_user_id() OR app.is_system())
  WITH CHECK (id = app.current_user_id() OR app.is_system());
CREATE POLICY rls_usuario_delete ON "Usuario" FOR DELETE
  USING (id = app.current_user_id() OR app.is_system());

-- Endereco: do dono; também legível quando é o local de um anúncio visível.
CREATE POLICY rls_endereco_select ON "Endereco" FOR SELECT USING (
  cliente_id = app.current_user_id() OR app.is_system()
  OR EXISTS (SELECT 1 FROM "Anuncio" a WHERE a.endereco_id = "Endereco".id)
);
CREATE POLICY rls_endereco_write ON "Endereco" FOR INSERT
  WITH CHECK (cliente_id = app.current_user_id() OR app.is_system());
CREATE POLICY rls_endereco_update ON "Endereco" FOR UPDATE
  USING (cliente_id = app.current_user_id() OR app.is_system())
  WITH CHECK (cliente_id = app.current_user_id() OR app.is_system());
CREATE POLICY rls_endereco_delete ON "Endereco" FOR DELETE
  USING (cliente_id = app.current_user_id() OR app.is_system());

-- Categoria: catálogo público, somente leitura para a API (seed via admin).
CREATE POLICY rls_categoria_select ON "Categoria" FOR SELECT USING (true);

-- Anuncio: ATIVO é público; lixeira/removido só para o dono (ou para quem o
-- favoritou, para "Meus Favoritos" mostrá-lo como indisponível). Escrita só
-- pelo anunciante; a purga CRON roda como sistema.
CREATE POLICY rls_anuncio_select ON "Anuncio" FOR SELECT USING (
  status = 'ATIVO' OR anunciante_id = app.current_user_id() OR app.is_system()
  OR EXISTS (
    SELECT 1 FROM "Favorito" f
    WHERE f.anuncio_id = "Anuncio".id AND f.cliente_id = app.current_user_id()
  )
);
CREATE POLICY rls_anuncio_insert ON "Anuncio" FOR INSERT
  WITH CHECK (anunciante_id = app.current_user_id() OR app.is_system());
CREATE POLICY rls_anuncio_update ON "Anuncio" FOR UPDATE
  USING (anunciante_id = app.current_user_id() OR app.is_system())
  WITH CHECK (anunciante_id = app.current_user_id() OR app.is_system());
CREATE POLICY rls_anuncio_delete ON "Anuncio" FOR DELETE
  USING (anunciante_id = app.current_user_id() OR app.is_system());

-- Imagem: herda a visibilidade do anúncio; escrita só pelo dono do anúncio.
CREATE POLICY rls_imagem_select ON "Imagem" FOR SELECT USING (
  EXISTS (SELECT 1 FROM "Anuncio" a WHERE a.id = "Imagem".anuncio_id)
);
CREATE POLICY rls_imagem_insert ON "Imagem" FOR INSERT WITH CHECK (
  app.is_system() OR EXISTS (
    SELECT 1 FROM "Anuncio" a
    WHERE a.id = "Imagem".anuncio_id AND a.anunciante_id = app.current_user_id()
  )
);
CREATE POLICY rls_imagem_delete ON "Imagem" FOR DELETE USING (
  app.is_system() OR EXISTS (
    SELECT 1 FROM "Anuncio" a
    WHERE a.id = "Imagem".anuncio_id AND a.anunciante_id = app.current_user_id()
  )
);

-- Favorito: estritamente do próprio cliente.
CREATE POLICY rls_favorito_all ON "Favorito" FOR ALL
  USING (cliente_id = app.current_user_id() OR app.is_system())
  WITH CHECK (cliente_id = app.current_user_id() OR app.is_system());

-- Tabelas internas de segurança: só o servidor, nunca em nome de um usuário.
CREATE POLICY rls_recuperacao_system ON "RecuperacaoSenha" FOR ALL
  USING (app.is_system()) WITH CHECK (app.is_system());
CREATE POLICY rls_tentativa_system ON "TentativaLogin" FOR ALL
  USING (app.is_system()) WITH CHECK (app.is_system());
CREATE POLICY rls_token_system ON "TokenRevogado" FOR ALL
  USING (app.is_system()) WITH CHECK (app.is_system());
